on:
  # On push/pr & weekly
  push:
  pull_request:
  schedule:
    - cron: "0 23 * * 0"

name: CI

jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch minsign 0.8 release
        run: |
          wget \
            https://github.com/jedisct1/minisign/releases/download/0.8/minisign-0.8.tar.gz \
            https://github.com/jedisct1/minisign/releases/download/0.8/minisign-0.8.tar.gz.minisig
      - name: verify minisign 0.8 release
        uses: ./
        with:
          args: -Vm "minisign-0.8.tar.gz" -P "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"
  sign:
    name: "Sign"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate a test key
        uses: ./
        with:
          args: -G
      - name: Create test file to sign
        run: dd if=/dev/urandom bs=4k count=1 of=test-file.bin
      - name: Sign our test file
        uses: ./
        with:
          args: -Sm test-file.bin
      - name: Verify the signature still works
        uses: ./
        with:
          args: -Vm test-file.bin

